name: flutter_minio_file_manager
description: A MinIO-based file management Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter

#   minio: ^3.5.7
#   riverpod: ^2.4.4      # 状态管理
#   file_picker: ^5.3.1   # 文件选择
#   path_provider: ^2.0.15 # 路径获取
#   dio: ^5.4.3           # 网络请求
#   synchronized: ^3.1.0  # 并发控制
#   percent_indicator: ^4.2.2 # 进度条
#   path: ^1.8.3
#   crypto: ^3.0.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  minio: ^3.5.7
  intl: ">=0.19.0 <0.21.0"
  path_provider: ^2.0.15
  file_picker: ^5.3.2
  provider: ^6.0.5
  crypto: ^3.0.3
  path: ^1.8.3
  universal_html: ^2.2.3
  shared_preferences: ^2.1.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true